### ISSUE TITLE
Ion fails to load vertically long images

### ISSUE THREAD

**Issue by mightyfrog** [koush/ion#485] opened 2015-02-07 16:56 UTC
Happens when Ion tries to load multiple images in recycled views (ViewHolder pattern).

**Comment by mightyfrog** [comment] 2015-02-10 19:16
Some workarounds for those having the same issue:
1. picasso/glide both can handle this type of images in recycled views
2. enable deepzoom if image quality doesn't matter
3. this is a regression bug introduced last August, so make a build from older commits, expect a lot of OutOfMemoryError's from ByteBufferList though
4. simply don't use recycled view

**Comment by koush** [comment] 2015-02-10 22:02
Ion does those fine. I exclusively use recycled views to prevent excess allocations.

**Comment by koush** [comment] 2015-02-10 22:07
Will need some code.

**Comment by mightyfrog** [comment] 2015-02-11 07:48
https://github.com/mightyfrog/ion_test.git

**Comment by koush** [comment] 2015-02-12 05:35
Seems fine here. Can you submit a movie of the issue?

**Comment by mightyfrog** [comment] 2015-02-12 17:31
You can pull three movies:
ion_bug.mp4, ion_ok.mp4 (with normal size images), picasso.mp4 (same code with picasso)

**Comment by koush** [comment] 2015-02-12 20:18
Ok, that's not what I am seeing at all. Mine looks like ion ok. Though I compiled against master. Let me try compiling against the jars.

**Comment by koush** [comment] 2015-02-12 20:22
What device are you testing on?

**Comment by mightyfrog** [comment] 2015-02-13 17:34
Nexus 5. I'm pretty sure this happens on other devices. I found this bug through user reviews for one of our apps. This particular app was using very old Ion from last July. Upon updating Ion to the latest, we got many reviews saying images are broken. It was reproducible on all QA devices we used.

**Comment by koush** [comment] 2015-02-14 07:04
Can you enable verbose logging on the requests and also add a callback to the imageview load and watch for exceptions?

```java
onCreate
        Ion.getDefault(this).configure().setLogging("IonTest", Log.VERBOSE);
```

```java

            Ion.with(holder.iv).load(URLS[position])
            .setCallback(new FutureCallback<ImageView>() {
                @Override
                public void onCompleted(Exception e, ImageView result) {
                    if (e != null)
                        e.printStackTrace();
                }
            });
```

**Comment by mightyfrog** [comment] 2015-02-16 06:22
I'll update the test code and get some logs.

**Comment by mightyfrog** [comment] 2015-02-16 16:03
I figured out this bug happens when you have tall images and short images coexist in the adapter. I added the same short image in three places. Please see updated ion_bug.mp4.

Somehow the log doesn't contain any information of the images affected by this bug. There's something weird going on.

https://github.com/mightyfrog/ion_test/commit/30325be19f63c6a005782f96c9f38b96e25ce0a5

**Comment by koush** [comment] 2015-02-16 19:26
Yeah I thought it may be a network error, since I could not reproduce it. Will check with your new repro steps

**Comment by koush** [comment] 2015-02-17 01:12
Cool, fixed with 51f4661

**Closed by koush** 2015-02-17 01:12 UTC

**Comment by koush** [comment] 2015-02-17 01:15
Generally, ion tries to use the imageview's existing size to figure out what sample size to use when loading the bitmap to save memory. This works well if the imageview is a constant size, regardless of the image being loaded.

But, adjustViewBounds makes the imageview resize to random sizes, which throws misleading values to the sample size on bitmap decode.

**Comment by mightyfrog** [comment] 2015-02-17 14:11
I'll test it and let you know.

**Comment by mightyfrog** [comment] 2015-02-20 02:48
The fix is good. Thanks.
